### ISSUE TITLE
pip install -r requirements.txt causing errors

### ISSUE THREAD

**Issue by FrankAIUser** [hacksider/Deep-Live-Cam#117]
I have set up my venv already.
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_internal\utils\misc.py", line 706, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\frank\desktop\Deep-Live-Cam-main\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\frank\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\frank\AppData\Local\Temp\pip-build-env-fmyats2a\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

**Comment by Updatedme** [comment]
Try degrad them .

**Comment by matas0** [comment]
The error is because of the missing `distutils` module, it's not included in Python 3.12 by default. 

Downgrade your python version to python 3.10 as recommended and it should be fixed.

**Comment by TheJackiMonster** [comment]
> Downgrade your python version to python 3.10 as recommended and it should be fixed.

It's not really a fix but a workaround. If a module is not included in newer Python versions, it shouldn't be used in the first place.

**Comment by TheJackiMonster** [comment]
None is fixed, Python 3.12 still fails to build.

**Comment by Updatedme** [comment]
> None is fixed, Python 3.12 still fails to build.

Degrade to python 3.10

**Comment by vic4key** [comment]
We recommended Python 3.10; other versions are optional and not treated as bugs. Full support for other versions may be available later, but not currently.

**Comment by TheJackiMonster** [comment]
> We recommended Python 3.10; other versions are optional and not treated as bugs. Full support for other versions may be available later, but not currently.

If we already go "it works on my machine" approach, why not ship a docker image? It should never be a user's responsibility to figure out dependencies. Multiple times this has resulted in avoidable issues for people.

Also for every developer who uses a stable rolling release operating system, this is just annoying to deal with. At this point it would make way more sense to run the whole application inside a sandbox if you need that kind of controlled environment.

**Comment by vic4key** [comment]
@TheJackiMonster Why don't you follow the instruction that using the Python 3.10?
It's open source and being under the development time, we don't have time to cover them all.
You should follow the instruction.

**Comment by TheJackiMonster** [comment]
> @TheJackiMonster Why don't you follow the instruction that using the Python 3.10? It's open source and being under the development time, we don't have time to cover them all. You should follow the instruction.

I don't have an issue with it not getting fixed immediately. I know that open-source projects have limited resources. But even if time is limited, it doesn't make sense to close issues like this without proper solution.

People will continue to have the same issue. They will continue reporting this issue, causing a lot of duplicates because nobody searches in already closed issues. It makes way more sense to simply leave the issue open and refer to it. So people have a way to find the current workaround and it can actually be tracked when a MR solves the issue.

**Comment by hacksider** [comment]
Hi there @TheJackiMonster , the recommended is 3.10 as per readme. We're trying to resolve everything and most of it are already in the closed ticket. Other people are also trying to help. In case you have a solution aside from going to the recommended version, please feel free to push it to the experimental so we can also help others. 😊
