### ISSUE TITLE
Error - I use AMD graphics card - rx 580 

### ISSUE THREAD

**Issue by xzy71** [hacksider/Deep-Live-Cam#121]
Traceback (most recent call last):
  File "C:\Users\~~\Desktop\Deep-Live-Cam-main\modules\core.py", line 14, in <module>
    import torch
  File "C:\Users\~~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] Não foi possível encontrar o módulo especificado. Error loading "C:\Users\~~\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by royalleenoks** [comment]
looks like some files are missing, are you already running it using venv?

**Comment by royalleenoks** [comment]
install all dependencies when venv is activated
