### ISSUE TITLE
Don't running

### ISSUE THREAD

**Issue by Pshenichka** [hacksider/Deep-Live-Cam#138]
PS C:\DLC\Deep-Live-Cam> python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\DLC\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\DLC\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
  File "C:\Python310\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] Не найден указанный модуль. Error loading "C:\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by hacksider** [comment]
You havent installed torch

**Comment by Pshenichka** [comment]
But i instal requirements file

**Comment by hacksider** [comment]
What do you mean now it's insightface? Can you include the error message?

**Comment by Pshenichka** [comment]
After error with torch module, i reinstalled him, but run command still shows error with another modules, wich one i reinstalled too, but on insightface it keep showing error after reinstallation

PS C:\DLC\Deep-Live-Cam> python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\DLC\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\DLC\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\DLC\Deep-Live-Cam\modules\ui.py", line 10, in <module>
    from modules.face_analyser import get_one_face
  File "C:\DLC\Deep-Live-Cam\modules\face_analyser.py", line 2, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by billythekidprog** [comment]
I have the same error. I use W11.

**Comment by ramzai23rus** [comment]
I have the same error

**Comment by d9012218** [comment]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from modules import core
  File "C:\Users\USER\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Users\USER\Deep-Live-Cam\modules\ui.py", line 10, in <module>
    from modules.face_analyser import get_one_face
  File "C:\Users\USER\Deep-Live-Cam\modules\face_analyser.py", line 5, in <module>
    from modules.typing import Frame
  File "C:\Users\USER\Deep-Live-Cam\modules\typing.py", line 7, in <module>
    Frame = numpy.ndarray[Any, Any]

**Comment by KINGMUDDY** [comment]
File "C:\livecam\deep-live-cam\run.py", line 3, in <module>
    from modules import core
  File "C:\livecam\deep-live-cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\livecam\deep-live-cam\modules\ui.py", line 3, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'


how to get rid of this error

**Comment by exploretech** [comment]
> all this is related to experimental branch. main branch works perfectly fine

which is the main branch

**Comment by Mrviktur** [comment]
File "C:\Deep-Live-Cam-Improved-main\run.py", line 3, in <module>
    from modules import core
  File "C:\Deep-Live-Cam-Improved-main\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Deep-Live-Cam-Improved-main\modules\ui.py", line 6, in <module>
    from PIL import Image, ImageOps
  File "C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\__init__.py)

**Comment by ochristianlove** [comment]
[](https://github.com/hacksider/Deep-Live-Cam/issues/73)

i wrote the solution here, enjoy
