### ISSUE TITLE
CUDA Error 

### ISSUE THREAD

**Issue by SSalvadoRR-official** [hacksider/Deep-Live-Cam#141]
4070 Ti
7500F
Installer said it is installing cuda 11.8
![Screenshot_291](https://github.com/user-attachments/assets/2d130b96-e5af-4190-acc4-058f54850c2e)

```
C:\Users\Ranazy\Deep-Live-Cam>python run.py --execution-provider cuda
Frame processor face_enhancer not found
Frame processor face_enhancer not found
2024-08-10 14:57:54.3535031 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Ranazy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-08-10 14:57:54.4467162 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Ranazy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Ranazy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Ranazy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

**Comment by hacksider** [comment]
Please install the recommended cuda version
![image](https://github.com/user-attachments/assets/6a2ae6a4-1489-49a7-a940-71bb2cee5bfc)

**Comment by SSalvadoRR-official** [comment]
Am I doing something wrong here? 
![Uploading b8615ceb-5cf7-4f7b-997b-06bb06fe758a.jpg…]()

**Comment by SSalvadoRR-official** [comment]
Am I doing something wrong here?
![b8615ceb-5cf7-4f7b-997b-06bb06fe758a](https://github.com/user-attachments/assets/bd409fe7-0dd3-4d0a-9ef8-a1e513966f37)

**Comment by SSalvadoRR-official** [comment]
![Screenshot_292](https://github.com/user-attachments/assets/6f6b7101-ddfa-441a-b203-a4882c8740db)
There they are, all 11.8

**Comment by Dimarom4** [comment]
same problem with rtx 3070 and right version CUDA
![image](https://github.com/user-attachments/assets/b8a05b6d-2065-4e8a-9130-cff3100e7094)
![image](https://github.com/user-attachments/assets/4f5d7835-828b-4293-985f-7d2f884bf747)
