### ISSUE TITLE
wont start:   ImportError: cannot import name 'model_zoo' from 'insightface.model_zoo' (unknown location)

### ISSUE THREAD

**Issue by fritol** [hacksider/Deep-Live-Cam#197]
on WIN 11 in venv pyton 3.10
all installed fine including `visual studio 2022 runtimes`
`nvcc -V` shows 11.8

```
 D:\Deep-Live-Cam>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "D:\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "D:\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "D:\Deep-Live-Cam\modules\ui.py", line 10, in <module>
    from modules.face_analyser import get_one_face
  File "D:\Deep-Live-Cam\modules\face_analyser.py", line 5, in <module>
    from modules.typing import Frame
  File "D:\Deep-Live-Cam\modules\typing.py", line 3, in <module>
    from insightface.app.common import Face
  File "D:\Deep-Live-Cam\insightface\python-package\insightface\app\__init__.py", line 1, in <module>
    from .face_analysis import *
  File "D:\Deep-Live-Cam\insightface\python-package\insightface\app\face_analysis.py", line 17, in <module>
    from ..model_zoo import model_zoo
ImportError: cannot import name 'model_zoo' from 'insightface.model_zoo' (unknown location)
```

**Comment by Hello307430** [comment]
I also encountered the same problem.   Have you solved the problem there?
