### ISSUE TITLE
Memory Setting not working

### ISSUE THREAD

**Issue by fiete96** [hacksider/Deep-Live-Cam#205]
Hey,
I got this error message:

```
(Deep-Live-cam) XXX@XXX % python run.py --max-memory 20 --execution-provider coreml --execution-threads 12

Traceback (most recent call last):
  File "/Users/XXX/Documents/XXX/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/XXX/Documents/XXX/Deep-Live-Cam/modules/core.py", line 242, in run
    limit_resources()
  File "/Users/XXX/Documents/XXX/Deep-Live-Cam/modules/core.py", line 145, in limit_resources
    resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))
OverflowError: Python int too large to convert to C long
```

I got an m3 Max CPU with 36GB of Memory. without the --max-memory 20 it works!

**Comment by thelouisgan** [comment]
Same issue here..
