### ISSUE TITLE
Can't run run.py

### ISSUE THREAD

**Issue by MinhHanZo** [hacksider/Deep-Live-Cam#213]
i already downloaded torch and other files but i got this msg 
![image](https://github.com/user-attachments/assets/640b45eb-c6c8-47a3-ad63-912ec26116ce)

**Comment by adithya-ac** [comment]
Same error...

> C:\Users\<user>\Desktop\Deep\Deep-Live-Cam>python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Traceback (most recent call last):
  File "C:\Users\<user>\Desktop\Deep\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\<user>\Desktop\Deep\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Users\<user>\Desktop\Deep\Deep-Live-Cam\modules\ui.py", line 3, in <module>
    import customtkinter as ctk
  File "C:\Users\<user>\AppData\Roaming\Python\Python310\site-packages\customtkinter\__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
ModuleNotFoundError: No module named 'tkinter'
