### ISSUE TITLE
Frame processor face_enhancer not found + problem start live

### ISSUE THREAD

**Issue by kreniov** [hacksider/Deep-Live-Cam#219]
python run.py --execution-provider cuda
Frame processor face_enhancer not found
Frame processor face_enhancer not found
2024-08-12 20:50:48.1133635 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-08-12 20:50:48.2467873 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
                                                                                   ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by Ku-Tadao** [comment]
This **_should_** resolve the face_enhancer issue:

 uninstall the current version of basicsr:
`pip uninstall basicsr -y`

install basicsr directly from its GitHub repository:
`pip install git+https://github.com/xinntao/BasicSR.git@master`

After installation is complete, also reinstall gfpgan:
`pip uninstall gfpgan -y`
`pip install git+https://github.com/TencentARC/GFPGAN.git@master`

this fixed it for me, but now my next issue is, why is everything 1FPS when i click on Live.

**Comment by Dimarom4** [comment]
I have the same problem with `Frame processor face_enhancer not found`. Then i did what you say

> This **_should_** resolve the face_enhancer issue:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> this fixed it for me, but now my next issue is, why is everything 1FPS when i click on Live.

And it helps. But only in mode without CUDA. And i also have 1FPS
In the CUDA mode i have 
```
(env) PS D:\Рабочий стол\Deep-Live-Cam-main> python run.py --execution-provider cuda
2024-08-13 13:43:34.1056150 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntime
Error] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN
 as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-08-13 13:43:34.2091925 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntime
Error] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and 
cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

```

**Comment by kreniov** [comment]
![Снимок экрана 2024-08-13 181551](https://github.com/user-attachments/assets/d077d1c9-a0c3-4331-926a-d6af0daa72f7)
C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main>python run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\I1YK9N/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\I1YK9N/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\I1YK9N/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\I1YK9N/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\I1YK9N/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
                                                                                   ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 286, in webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'normed_embedding'
-------------------------------------------
Also, when using cuda, it comes out -
C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main>python run.py --execution-provider cuda
2024-08-13 18:20:43.1779135 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-08-13 18:20:43.3105173 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
                                                                                   ^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\Desktop\Deep-Live-Cam-main\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\I1YK9N\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
------------------------
I installed cuda 11.8 for nvidia - it didn't work. I installed version 12 - it didn't help either. I manually installed cudnn 9.3.0 in each version since it simply did not exist

**Comment by kreniov** [comment]
What you recommended to install is installed. Surprisingly, they were not installed at all

**Comment by Dimarom4** [comment]
I also manually installed cudnn but nothing has changed

**Comment by yalmathami** [comment]
just install gfpgan. Its tool used to save the network in face_enhancer object, hence, you will have face_enhancer.

**Comment by Morganbsl** [comment]
> I also manually installed cudnn but nothing has changed

download and install cudnn version v8.6.0 ([click here](https://developer.nvidia.com/compute/cudnn/secure/8.6.0/local_installers/11.8/cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip)) bc it compatible with cuda 11.8

or click on this link and scroll till you find **Download cuDNN v8.6.0 (October 3rd, 2022), for CUDA 11.x** and click on it and download the zip file **Local Installer for Windows (Zip)**, link : 
https://developer.nvidia.com/rdp/cudnn-archive#a-collapse860-118

after installing it, then open cmd in the same directory where project running and before running the main script past this codes : 

1 :
`set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8"
`

2 : 
`set "PATH=%CUDA_PATH%\bin;%PATH%"
`

and then activate the environment : 
`venv\Scripts\activate
`

and then run the script : 
`run.py --execution-provider cuda
`

now it should run with the gpu enabled

**Comment by CASCAD-LLC** [comment]
> > Я также вручную установил cudnn, но ничего не изменилось.
> 
> скачайте и установите cudnn версии v8.6.0 ( [нажмите здесь](https://developer.nvidia.com/compute/cudnn/secure/8.6.0/local_installers/11.8/cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip) ), так как она совместима с cuda 11.8
> 
> или нажмите на эту ссылку и прокрутите, пока не найдете **Загрузить cuDNN v8.6.0 (3 октября 2022 г.) для CUDA 11.x** , нажмите на нее и загрузите zip-файл **Local Installer для Windows (Zip)** , ссылка: https://developer.nvidia.com/rdp/cudnn-archive#a-collapse860-118
> 
> после установки откройте cmd в том же каталоге, где запущен проект, и перед запуском основного скрипта пропустите эти коды:
> 
> 1 : `set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" `
> 
> 2 : `set "PATH=%CUDA_PATH%\bin;%PATH%" `
> 
> и затем активируйте среду: `venv\Scripts\activate `
> 
> и затем запустите скрипт: `run.py --execution-provider cuda `
> 
> теперь он должен работать с включенным графическим процессором

**Comment by ObjectiveTruth** [comment]
> I have the same problem with `Frame processor face_enhancer not found`. Then i did what you say
> 
> > This **_should_** resolve the face_enhancer issue:
> > uninstall the current version of basicsr: `pip uninstall basicsr -y`
> > install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> > After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> > this fixed it for me, but now my next issue is, why is everything 1FPS when i click on Live.
> 
> And it helps. But only in mode without CUDA. And i also have 1FPS In the CUDA mode i have
> 
> ```
> (env) PS D:\Рабочий стол\Deep-Live-Cam-main> python run.py --execution-provider cuda
> 2024-08-13 13:43:34.1056150 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntime
> Error] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
> 
> EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN
>  as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
>  when using ['CUDAExecutionProvider']
> Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
> 2024-08-13 13:43:34.2091925 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntime
> Error] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "D:\pyprog\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
>     sess.initialize_session(providers, provider_options, disabled_optimizers)
> RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and 
> cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
> ```

This worked for me on MacOS, though now it's 1FPS. My guess is something around the coreml not being used since I can hear the whole computer about to take off from the fans (M1 mac btw)

**Comment by Ku-Tadao** [comment]
honestly, give up on the whole project.

Deep Live Cam in the end remained partial open source, because they're still using inswapper_128_fp16 publicly, which simply said, is **outdated** and their online services use the 512 modal

**Comment by Ogdreamchaser** [comment]
Got it ✅ — the problem isn’t the .pth file placement, it’s that DeepLiveCam doesn’t see the face_enhancer processor at all, so it’s not even trying to use GFPGAN.

That error:

Frame processor face_enhancer not found
Warning: Failed to load frame processor face_enhancer requested by UI state.


means the repo you cloned either:

Doesn’t have face_enhancer integration enabled (some forks stripped it out), or

The frame_processors list in the code doesn’t include it.

🔎 How to fix

Open run.py (or core/frame_processors/ folder if it exists).

You should see files like face_swapper.py, face_enhancer.py.

If face_enhancer.py is missing, your fork doesn’t support it.

Check core/frame_processors/__init__.py.

It should have something like:

from .face_swapper import FaceSwapper
from .face_enhancer import FaceEnhancer


If the face_enhancer import isn’t there, it won’t register.

In run.py, look for where frame_processors are loaded. It must include "face_enhancer".
Example:

FRAME_PROCESSORS = {
    "face_swapper": FaceSwapper,
    "face_enhancer": FaceEnhancer,
}

✅ What you should do

If your repo doesn’t have face_enhancer.py, then the HuggingFace release you cloned doesn’t support GFPGAN/CodeFormer yet. You’ll need to either:

Switch to a fork that supports it, or

Add face_enhancer.py manually (I can give you a working template).

If the file exists but isn’t imported, just add it to __init__.py and run.py.

👉 Do you want me to give you the missing face_enhancer.py code so you can drop it into core/frame_processors/ and enable GFPGAN?

You said:
YES GIVE ME THE CODE
ChatGPT said:

Perfect 👍 — let’s wire up face_enhancer for DeepLiveCam.
We’ll build a face_enhancer.py processor that uses GFPGAN (and optionally CodeFormer if you want).

📂 Where to put it

Create this file in:

Deep-Live-Cam/core/frame_processors/face_enhancer.py

📝 Code for face_enhancer.py
import cv2
import numpy as np
import torch
import os

from gfpgan import GFPGANer


class FaceEnhancer:
    def __init__(self, model_path=None, upscale=2, arch='clean', channel_multiplier=2, bg_upsampler=None):
        """
        Face enhancer using GFPGAN.
        :param model_path: Path to GFPGAN .pth model
        :param upscale: Upscaling factor
        :param arch: Model architecture (default: 'clean')
        :param channel_multiplier: GFPGAN channel multiplier
        :param bg_upsampler: Optional background upsampler (e.g. Real-ESRGAN)
        """
        if model_path is None:
            # Default expected location inside Deep-Live-Cam
            model_path = os.path.join("weights", "GFPGANv1.4.pth")

        if not os.path.exists(model_path):
            raise FileNotFoundError(f"GFPGAN model not found at {model_path}")

        # Initialize GFPGAN
        self.gfpganer = GFPGANer(
            model_path=model_path,
            upscale=upscale,
            arch=arch,
            channel_multiplier=channel_multiplier,
            bg_upsampler=bg_upsampler
        )

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """
        Enhance a single video frame.
        :param frame: BGR numpy image
        :return: Enhanced BGR numpy image
        """
        try:
            cropped_faces, restored_faces, restored_img = self.gfpganer.enhance(
                frame,
                has_aligned=False,
                only_center_face=False,
                paste_back=True
            )
            return restored_img
        except Exception as e:
            print(f"[FaceEnhancer] Enhancement failed: {e}")
            return frame

🔧 Next steps to enable it

Add it to the imports in
core/frame_processors/__init__.py:

from .face_swapper import FaceSwapper
from .face_enhancer import FaceEnhancer


Register it in run.py where frame processors are mapped:

FRAME_PROCESSORS = {
    "face_swapper": FaceSwapper,
    "face_enhancer": FaceEnhancer,
}


Place your GFPGAN model (GFPGANv1.4.pth) into:

Deep-Live-Cam/weights/GFPGANv1.4.pth


Run with:

python run.py --execution-provider cuda --frame-processor face_enhancer
