### ISSUE TITLE
Error while uploading certain images

### ISSUE THREAD

**Issue by marcorossi2024** [hacksider/Deep-Live-Cam#238]
when I upload some source images I get the following error:

Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/opt/homebrew/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/Users/lc/Documents/Dev/deep-live-cam/Deep-Live-Cam/modules/ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "/Users/lc/Documents/Dev/deep-live-cam/Deep-Live-Cam/modules/ui.py", line 286, in webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "/Users/lc/Documents/Dev/deep-live-cam/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "/Users/lc/Documents/Dev/deep-live-cam/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/opt/homebrew/lib/python3.10/site-packages/insightface/model_zoo/inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'

**Comment by Pancat007** [comment]
same issue here, do we have any solution?

**Comment by Rokkonrol** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/87#issuecomment-2278889528 #

**Comment by marcorossi2024** [comment]
In my case it happens only with certain images. Maybe when the crop is too close to the edges of the face?
________________________________

**Comment by x011** [comment]
The image needs to include a bit of the shoulders or it won't be recognized.
