### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'config'

### ISSUE THREAD

**Issue by diffussy69** [hacksider/Deep-Live-Cam#239]
PS C:\Deep-Live-Cam\Deep-Live-Cam> python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\Deep-Live-Cam\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "C:\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 242, in run
    limit_resources()
  File "C:\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 131, in limit_resources
    gpus = tensorflow.config.experimental.list_physical_devices('GPU')
AttributeError: module 'tensorflow' has no attribute 'config'
PS C:\Deep-Live-Cam\Deep-Live-Cam>

**Comment by diffussy69** [comment]
Same error trying to run without CUDA

PS C:\Deep-Live-Cam\Deep-Live-Cam> python run.py
Traceback (most recent call last):
  File "C:\Deep-Live-Cam\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "C:\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 242, in run
    limit_resources()
  File "C:\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 131, in limit_resources
    gpus = tensorflow.config.experimental.list_physical_devices('GPU')
AttributeError: module 'tensorflow' has no attribute 'config'

**Comment by tekinarslan** [comment]
You can replace your tensorflow with latest one 2.17.0 and update requirements file for new tensorflow version. I skip this error but My program still is not working. It can't start download faces.

**Comment by diffussy69** [comment]
**SOLVED**

cd into your venv and run: pip install tensorflow --upgrade
