### ISSUE TITLE
Have an issue with start

### ISSUE THREAD

**Issue by kreenjeee** [hacksider/Deep-Live-Cam#246]
Make everything from guide but...
![image](https://github.com/user-attachments/assets/683151eb-9e7f-4084-94a1-3b43ead79864)

**Comment by kreenjeee** [comment]
installed CTK but 
![image](https://github.com/user-attachments/assets/acb7afd4-3159-4b2c-93a7-d256da1c9e12)

**Comment by Mrkomiljon** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
