### ISSUE TITLE
Can it be used for mac mini

### ISSUE THREAD

**Issue by libai-lab** [hacksider/Deep-Live-Cam#307]
Can it be used for mac mini m2?

**Comment by nblasgen** [comment]
There are instructions on the main page for how to install on Apple Silicon (M1, M2, M3, M4).  Anything specific you're having trouble with?  FAQ covers the issues that the install doesn't.

**Comment by APD-01** [comment]
I have it running on 2020 M1 mini.  I had to install the tk- toolkit to make the gui appear.
Look at the error the phyton throws and feed it to GPT.  It will tell you what you need to do, and the steps.

**Comment by libai-lab** [comment]
> 我在 2020 M1 mini 上运行它。我必须安装 tk- 工具包才能显示 gui。查看 phyton 抛出的错误并将其提供给 GPT。它会告诉您需要做什么以及步骤。

Can it run on 8g RAM

**Comment by APD-01** [comment]
> > 我在 2020 M1 mini 上运行它。我必须安装 tk- 工具包才能显示 gui。查看 phyton 抛出的错误并将其提供给 GPT。它会告诉您需要做什么以及步骤。
> 
> Can it run on 8g RAM

That I can't answer, sorry.  I have 16GB. It's not rocket fast, but it gets the job down.  It does slow the mac down a fair bit too while it's running.. but it runs.

**Comment by vhbsouza** [comment]
Just followed the steps on Mac Mini M2 PRO 16BG and I'm getting this error.

Can you help me?


```
Traceback (most recent call last):
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/modules/core.py", line 20, in <module>
    import modules.ui as ui
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/modules/ui.py", line 10, in <module>
    from modules.face_analyser import get_one_face, get_unique_faces_from_target_image, get_unique_faces_from_target_video, add_blank_map, has_valid_map, simplify_maps
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/modules/face_analyser.py", line 4, in <module>
    import insightface
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/app/mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/albumentations/__init__.py", line 6, in <module>
    from .augmentations import *
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/albumentations/augmentations/__init__.py", line 1, in <module>
    from .blur.functional import *
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/functional.py", line 9, in <module>
    from albucore.utils import clipped, maybe_process_in_chunks, preserve_channel_dim
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (/Users/test-env/Projects/labs/Deep-Live-Cam/venv/lib/python3.10/site-packages/albucore/utils.py)
```
