### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ManojINaik** [hacksider/Deep-Live-Cam#332]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\manoj\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\manoj\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "M:\faceswap\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "M:\faceswap\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "M:\faceswap\Deep-Live-Cam\Deep-Live-Cam\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "M:\faceswap\Deep-Live-Cam\Deep-Live-Cam\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\Users\manoj\AppData\Roaming\Python\Python310\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by liu-huo** [comment]
模型未导入，查看下路径，models下面是buffalo_l文件夹，buffalo_l文件夹下面是xxx.onnx权重文件（5个）

**Comment by manoj698** [comment]
plz can you guide me to solve this error clearly?

**Comment by manoj698** [comment]
> The model is not imported. Check the path. Under models is the buffalo_l folder, and under the buffalo_l folder are xxx.onnx weight files (5)

there is no buffalo_I folder
