### ISSUE TITLE
Worked perfectly yesterday but not today anymore

### ISSUE THREAD

**Issue by temtekmedia** [hacksider/Deep-Live-Cam#374]
C:\Users\Mylly\Deep-Live-Cam>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\Users\Mylly\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\Mylly\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Users\Mylly\Deep-Live-Cam\modules\ui.py", line 11, in <module>
    from modules.capturer import get_video_frame, get_video_frame_total
  File "C:\Users\Mylly\Deep-Live-Cam\modules\capturer.py", line 4, in <module>
    def get_video_frame(video_path: str, frame_number: int = 0) -> Any:
NameError: name 'Any' is not defined. Did you mean: 'any'?

C:\Users\Mylly\Deep-Live-Cam>python3 run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\Users\Mylly\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\Mylly\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

C:\Users\Mylly\Deep-Live-Cam>

I didnt touch anything, it just doesnt work anymore. Did i open it wrongly or?

**Comment by temtekmedia** [comment]
Allright I changed the "Any" to "any" in the capturer.py and it seems to open atleast
