### ISSUE TITLE
Error when trying to launch experimental build

### ISSUE THREAD

**Issue by Aikpo** [hacksider/Deep-Live-Cam#385]
Deep-Live-Cam-experimental> python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\Users\megam\Downloads\Deep-Live-Cam-experimental\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\megam\Downloads\Deep-Live-Cam-experimental\modules\core.py", line 21, in <module>
    import modules.ui as ui
  File "C:\Users\megam\Downloads\Deep-Live-Cam-experimental\modules\ui.py", line 9, in <module>
    from pygrabber.dshow_graph import FilterGraph
  File "C:\Users\megam\AppData\Local\Programs\Python\Python310\lib\site-packages\pygrabber\dshow_graph.py", line 40, in <module>
    from comtypes import GUID, COMError, COMObject, client
  File "C:\Users\megam\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\__init__.py", line 375
    except COMError, err:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by jayasafunctionofe** [comment]
potentially same issue as https://github.com/hacksider/Deep-Live-Cam/issues/394
