### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by sunyiwk** [hacksider/Deep-Live-Cam#387]
(base) M:\Deep-Live-Cam>python run.py
D:\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\admin/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\admin/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\admin/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
set det-size: (640, 640)
[DLC.FACE-SWAPPER] Progressing...
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\anaconda3\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "M:\Deep-Live-Cam\modules\ui.py", line 95, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "M:\Deep-Live-Cam\modules\ui.py", line 192, in select_output_path
    start()
  File "M:\Deep-Live-Cam\modules\core.py", line 182, in start
    frame_processor.process_image(modules.globals.source_path, modules.globals.output_path, modules.globals.output_path)
  File "M:\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 81, in process_image
    result = process_frame(source_face, target_frame)
  File "M:\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "M:\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "D:\anaconda3\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'reshape'

**Comment by pyr3xongithub** [comment]
Same error and I have ffmpeg installed, not sure what it means
