### ISSUE TITLE
win11 python=3.10 使用cpu运行 已经拉完了依赖，运行的时候出现报错AttributeError: 'NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by zuoliangyu** [hacksider/Deep-Live-Cam#402]

**Comment by zuoliangyu** [comment]
Traceback (most recent call last):
  File "C:\Users\zuolan\Desktop\face\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "C:\Users\zuolan\Desktop\face\Deep-Live-Cam\modules\core.py", line 236, in run
    if not pre_check():
  File "C:\Users\zuolan\Desktop\face\Deep-Live-Cam\modules\core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "C:\Users\zuolan\Desktop\face\Deep-Live-Cam\modules\core.py", line 166, in update_status
    ui.update_status(message)
  File "C:\Users\zuolan\Desktop\face\Deep-Live-Cam\modules\ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by zuoliangyu** [comment]
已解决，忘记安装ff了
