### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by c0mrad12** [hacksider/Deep-Live-Cam#412]
cmd used: python run.py

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 15, in <module>
    import onnxruntime
  File "C:\Python310\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Python310\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 33, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an exception set

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
  File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Python310\lib\site-packages\tensorflow\python\eager\context.py", line 33, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "C:\Python310\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
  File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\Python310\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\dtypes.py", line 29, in <module>
    from tensorflow.python.lib.core import _pywrap_bfloat16
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
  File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\Python310\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\dtypes.py", line 31, in <module>
    from tensorflow.python.lib.core import _pywrap_float8
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
  File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\Python310\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\dtypes.py", line 31, in <module>
    from tensorflow.python.lib.core import _pywrap_float8
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "C:\Users\conra\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\conra\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
  File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "C:\Python310\lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Python310\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Python310\lib\site-packages\tensorflow\python\data\util\nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "C:\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Python310\lib\site-packages\tensorflow\python\framework\dtypes.py", line 37, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle

**Comment by c0mrad12** [comment]
can sum1 help me bro

**Comment by Updatedme** [comment]
Tell me what type of laptop computer are you running 
What's the configuration?

**Comment by c0mrad12** [comment]
intel arc 770 gpu, 13th Gen Intel(R) Core cpu, 64gb ram, and a new clean installation of windows since it didnt work before i and i was having alot of pc freezing so i wiped it and installed windows 10 again, it got rid of the pc freezing but the program still didnt work

**Comment by c0mrad12** [comment]
> Tell me what type of laptop computer are you running What's the configuration?

intel arc 770 gpu, 13th Gen Intel(R) Core cpu, 64gb ram, and a new clean installation of windows since it didnt work before i and i was having alot of pc freezing so i wiped it and installed windows 10 again, it got rid of the pc freezing but the program still didnt work

**Comment by zhq426** [comment]
I also encountered this problem. Has it been solved?

**Comment by DealsBeam** [comment]
> > Tell me what type of laptop computer are you running What's the configuration?
> 
> intel arc 770 gpu, 13th Gen Intel(R) Core cpu, 64gb ram, and a new clean installation of windows since it didnt work before i and i was having alot of pc freezing so i wiped it and installed windows 10 again, it got rid of the pc freezing but the program still didnt work

Did you get it to work on Arc GPU?
