### ISSUE TITLE
requirements - Ubuntu 24

### ISSUE THREAD

**Issue by GinoMalatesta** [hacksider/Deep-Live-Cam#418]
Hi, I'm having lots of exceptions.
Ubuntu 24, Python 3.12, pip 24

Figured it out ... the module was removed from 3.12
ModuleNotFoundError: No module named 'distutils'

---

Installing Python 3.10 ...

It's going all the way thru collecting everything, but then it hangs at

Preparing metadata (setup.py) ... -

No errors, just hangs there ...

---

Tried again this morning, suddenly went further.
But throws lots of errors. Build ends with this:

Failed to build insightface basicsr filterpy
ERROR: Could not build wheels for insightface, basicsr, filterpy, which is required to install pyproject.toml-based projects

---

Installed python3.10-dev and libpython3.10-dev
It built insightface now, but still

ERROR: Could not build wheels for basicsr, filterpy, which is required to install pyproject.toml-based projects

**Comment by GinoMalatesta** [comment]
Whats missing?

**Comment by Updatedme** [comment]
What type of laptop computer is it ?
What's your laptop configuration

**Comment by GinoMalatesta** [comment]
It's a mini, Ryzen 7735 - Radeon x16, 32 GB DDR5 ...
Ubuntu 24.04 LTS comes with Python 3.12
I installed alternatives properly. 3.10 and 3.11
I wonder if gcc is the wrong version, or missing something ... gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

**Comment by GinoMalatesta** [comment]
created virtual environment CPython3.10.14.final.0-64 in 191ms
  creator CPython3Posix(dest=/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/gonzo/.local/share/virtualenv)
    added seed packages: pip==24.0, setuptools==68.1.2, wheel==0.42.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

---

Console quite similar for both failing:

      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rjituo28/filterpy_d8286705469243f099efdadf57a21622/setup.py", line 12, in <module>
          setup(
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 403, in run
          self.run_command("install")
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/command/install.py", line 78, in run
          return orig.install.run(self)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 708, in run
          self.run_command(cmd_name)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/home/gonzo/AI-Stuff/Deep-Live/Deep-Live-Cam/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?

**Comment by omega1996** [comment]
Ubuntu 24.04

requirements.txt

```
--extra-index-url https://download.pytorch.org/whl/cu121

numpy>=1.23.5,<2
typing-extensions>=4.8.0
opencv-python==4.10.0.84
cv2_enumerate_cameras==1.1.15
onnx==1.16.0
insightface==0.7.3
psutil==5.9.8
tk==0.1.0
customtkinter==5.2.2
pillow==11.1.0
torch==2.5.1+cu121; sys_platform != 'darwin'
torch==2.5.1+cu121; sys_platform == 'darwin'
torchvision==0.20.1; sys_platform != 'darwin'
torchvision==0.20.1+cu121; sys_platform == 'darwin'
onnxruntime-silicon==1.16.3; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.16.3; sys_platform != 'darwin'
tensorflow==2.14.0; sys_platform != 'darwin'
opennsfw2==0.10.2
protobuf==4.23.2
tqdm==4.66.4
gfpgan==1.3.8
tkinterdnd2==0.4.2
pygrabber==0.2
````

It at least runs, but Cuda 12.1 is not compatible with Ubuntu 24.04, so you can run only on CPU

**Comment by hacksider** [comment]
Please use the updated one yesterday.
