### ISSUE TITLE
What do I do when I get an error while running run.py

### ISSUE THREAD

**Issue by feiwuzhaohe** [hacksider/Deep-Live-Cam#442]
(ttt) D:\work\work_dir\数字\Deep-Live-Cam>python run.py --execution-provider cpu
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "D:\work\work_dir\数字\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "D:\work\work_dir\数字\Deep-Live-Cam\modules\core.py", line 240, in run
    if not pre_check():
  File "D:\work\work_dir\数字\Deep-Live-Cam\modules\core.py", line 162, in pre_check
    update_status('ffmpeg is not installed.')
  File "D:\work\work_dir\数字\Deep-Live-Cam\modules\core.py", line 170, in update_status
    ui.update_status(message)
  File "D:\work\work_dir\数字\Deep-Live-Cam\modules\ui.py", line 139, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by GLSYCOSMIC** [comment]
i have same question with you

**Comment by xjackzenvey** [comment]
uses ./start_portable_nvidia.bat instead of launching by run.py,which will not set the environment automatically

**Comment by rohitdash08** [comment]
@feiwuzhaohe, try installing ffmpeg first.

**Comment by budda** [comment]
```winget install --id Gyan.FFmpeg -e --source winget```

or use the supplied ```setup_deep_live_cam.bat``` file in the root of the repository to do it all for you.
