### ISSUE TITLE
Having These error when i run python run.py 

### ISSUE THREAD

**Issue by Underdome132** [hacksider/Deep-Live-Cam#49]
(tutorial_env) (base) C:\Users\under\Deep-Live-Cam>python run.py
Traceback (most recent call last):
  File "C:\Users\under\Deep-Live-Cam\run.py", line 15, in <module>
    import onnxruntime
  File "C:\Users\under\Deep-Live-Cam\tutorial_env\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\under\Deep-Live-Cam\tutorial_env\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\Deep-Live-Cam\tutorial_env\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.

**Comment by SanPatrick01** [comment]
‪+234 811 513 3627‬

Send pic here

**Comment by Maksim0905** [comment]
I have the same problem, how can I solve it?
