### ISSUE TITLE
couldn't connect to display

### ISSUE THREAD

**Issue by david-biro** [hacksider/Deep-Live-Cam#529]
On Windows 11, using Ubuntu subsystem (22.04.3.LTS) without exporting display variable (export DISPLAY=:0) the following error appears:

  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:0.0"

Maybe README.md should include this step also?

https://askubuntu.com/a/1418950

**Comment by david-biro** [comment]
I think this issue can be closed.

**Comment by meiling-fdu** [comment]
hello

could you please share the solution to this issue, thanks!

**Comment by david-biro** [comment]
> hello
> 
> could you please share the solution to this issue, thanks!

Hi

It depends whether you are using WSL1 or WSL2. Please share some details on your issue!

**Comment by meiling-fdu** [comment]
Traceback (most recent call last):
  File "/newdata/Deep-Live-Cam-main/run.py", line 6, in <module>
    core.run()
  File "/newdata/Deep-Live-Cam-main/modules/core.py", line 254, in run
    window = ui.init(start, destroy)
  File "/newdata/Deep-Live-Cam-main/modules/ui.py", line 64, in init
    ROOT = create_root(start, destroy)
  File "/newdata/Deep-Live-Cam-main/modules/ui.py", line 77, in create_root
    root = ctk.CTk()
  File "/root/anaconda3/envs/latenttracer/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 40, in __init__
    CTK_PARENT_CLASS.__init__(self, **pop_from_dict_by_set(kwargs, self._valid_tk_constructor_arguments))
  File "/root/anaconda3/envs/latenttracer/lib/python3.10/tkinter/__init__.py", line 2298, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"

The error is as above. I have no idea how to solve it…

**Comment by david-biro** [comment]
In a PowerShell terminal execute: **`wsl -l -v`** to see the version of your WSL.
If you have WSL1 then you need to install an X server on Windows (Xming, etc), while if you have WSL2 you no need to do that. The link above describes the options to configure DISPLAY variable depending on your environment.

So it would be good to know if you have Windows 10 or Windows 11, and WSL1 or WSL2.
