### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'configure' [DLC.CORE] ffmpeg is not installed.

### ISSUE THREAD

**Issue by qziov** [hacksider/Deep-Live-Cam#538]
Traceback (most recent call last):
  File "D:\ASoftwarespace\pythonProject\CatchFace\Deep-Live-Cam\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "D:\ASoftwarespace\pythonProject\CatchFace\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 240, in run
    if not pre_check():
  File "D:\ASoftwarespace\pythonProject\CatchFace\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 162, in pre_check
    update_status('ffmpeg is not installed.')
  File "D:\ASoftwarespace\pythonProject\CatchFace\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 170, in update_status
    ui.update_status(message)
  File "D:\ASoftwarespace\pythonProject\CatchFace\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 147, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'
[DLC.CORE] ffmpeg is not installed.

who can hlep me

**Comment by GD-bear** [comment]
README.md
