### ISSUE TITLE
deep live cam opens up but the preview never shows anything and it give the below error 

### ISSUE THREAD

**Issue by Underdome132** [hacksider/Deep-Live-Cam#54]
![Uploading Screenshot 2024-07-18 105337.png…]()
(base) C:\Users\under\Deep-Live-Cam>python run.py
ERROR:albumentations.check_version:Error fetching version info
Traceback (most recent call last):
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1035, in send
    self.connect()
  File "C:\Users\under\anaconda3\Lib\http\client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\under\anaconda3\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:983: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\under\anaconda3\Lib\site-packages\albumentations\check_version.py", line 29, in fetch_version_info
    with opener.open(url, timeout=2) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\urllib\request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:983: The handshake operation timed out>
Frame processor face_enhancer not found
Frame processor face_enhancer not found
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\under/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\under/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\under/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\under/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\under/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\under\anaconda3\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\under\Deep-Live-Cam\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
                                                                                   ^^^^^^^^^^^^^^^^
  File "C:\Users\under\Deep-Live-Cam\modules\ui.py", line 286, in webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 43, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\under\anaconda3\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\under\anaconda3\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\under\anaconda3\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\under\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.

**Comment by Decassidyc** [comment]
You did not do the below

3. Download Models
[GFPGANv1.4](https://huggingface.co/hacksider/deep-live-cam/resolve/main/GFPGANv1.4.pth)
[inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx)
Then put those 2 files on the "models" folder

**Comment by Underdome132** [comment]
i did that before getting the above errors

**Comment by Updatedme** [comment]
> i did that before getting the above errors

Did you put them in the right folder . 
Check that's you did so
