### ISSUE TITLE
运行run.py出错

### ISSUE THREAD

**Issue by 101testtime** [hacksider/Deep-Live-Cam#591]
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "C:\Users\24373\Desktop\Deep-Live-Cam-main\run.py", line 6, in <module>
    core.run()
  File "C:\Users\24373\Desktop\Deep-Live-Cam-main\modules\core.py", line 240, in run
    if not pre_check():
  File "C:\Users\24373\Desktop\Deep-Live-Cam-main\modules\core.py", line 162, in pre_check
    update_status('ffmpeg is not installed.')
  File "C:\Users\24373\Desktop\Deep-Live-Cam-main\modules\core.py", line 170, in update_status
    ui.update_status(message)
  File "C:\Users\24373\Desktop\Deep-Live-Cam-main\modules\ui.py", line 147, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

我已经安装了ffmpeg
facexlib                     0.3.0
ffmpeg                       1.4
filelock                     3.15.4

**Comment by mx-pai** [comment]
i have a same problem，have you solve it？

**Comment by hacksider** [comment]
Error says ffmpeg not installed. You can start with that by installing your ffmpeg ☺️

**Comment by hacksider** [comment]
As per the @101testtime it says
![image](https://github.com/user-attachments/assets/f671b05a-8891-4d5e-b539-21f156c4d8b1)

**Comment by junweipan** [comment]
If ffmpeg is not installed issue, follow this guide: https://github.com/hacksider/Deep-Live-Cam/issues/415
Restart your vs code or cmd to check` ffmpeg -version`
