### ISSUE TITLE
CUDA Package error

### ISSUE THREAD

**Issue by on-yes** [hacksider/Deep-Live-Cam#595]
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by on-yes** [comment]
[CUDA Package](https://github.com/hacksider/Deep-Live-Cam/releases/tag/cuda_deep-live-cam)

**Comment by hacksider** [comment]
That means it cant fetch the model from the said url /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

**Comment by on-yes** [comment]
> That means it cant fetch the model from the said url /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

download_path: K:\Deep-Live-Cam-cuda\tmp/.insightface\models\buffalo_l
Downloading K:\Deep-Live-Cam-cuda\tmp/.insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
Exception in Tkinter callback
Traceback (most recent call last):
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "K:\Deep-Live-Cam-cuda\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "K:\Deep-Live-Cam-cuda\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "K:\Deep-Live-Cam-cuda\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Deep-Live-Cam-cuda\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "K:\Deep-Live-Cam-cuda\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "K:\Deep-Live-Cam-cuda\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "K:\Deep-Live-Cam-cuda\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "K:\Deep-Live-Cam-cuda\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\insightface\utils\download.py", line 71, in download_file
    r = requests.get(url, stream=True)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "K:\Deep-Live-Cam-cuda\python\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by on-yes** [comment]
> That means it cant fetch the model from the said url /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

I have manually downloaded bufalo_1. zip，Put it in K:\Deep-Live-Cam-cuda\tmp\.insightface\models ，Then repeat the same mistake, what should I do

**Comment by on-yes** [comment]
> 尝试将 zip 文件解压缩到 models 文件夹，以便应用程序跳过该文件的下载 （+ 解压）。应如下所示：
> 
> ```
> models
> ├── buffalo_l
> │   ├── 1k3d68.onnx
> │   ├── 2d106det.onnx
> │   ├── det_10g.onnx
> │   ├── genderage.onnx
> │   └── w600k_r50.onnx
> └── buffalo_l.zip
> 
> 1 directory, 6 files
> ```
> 
> 对以相同方式失败的任何其他下载重复此过程。

Thanks

> Try extracting the zip file to the models folder so that the app skips the download (+ extraction) of that file. Should look something like this:
> 
> ```
> models
> ├── buffalo_l
> │   ├── 1k3d68.onnx
> │   ├── 2d106det.onnx
> │   ├── det_10g.onnx
> │   ├── genderage.onnx
> │   └── w600k_r50.onnx
> └── buffalo_l.zip
> 
> 1 directory, 6 files
> ```
> 
> Repeat the process for any other downloads that fails the same way.

Thanks
