### ISSUE TITLE
Cannot open app

### ISSUE THREAD

**Issue by nguyensi22** [hacksider/Deep-Live-Cam#606]
Traceback (most recent call last):
  File "D:\DATA2\AI-DEEP\Deepcamlive\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "D:\DATA2\AI-DEEP\Deepcamlive\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "D:\DATA2\AI-DEEP\Deepcamlive\Deep-Live-Cam\modules\ui.py", line 7, in <module>
    import tkinterdnd2 as tkdnd
ModuleNotFoundError: No module named 'tkinterdnd2'

I have installed 'tkinterdnd2' but when running the app it still gives me an error and does not enter the app interface

**Comment by hacksider** [comment]
kindly get the latest commit.

**Comment by markbland82** [comment]
I have the latest and am getting this error as well.
