### ISSUE TITLE
ERROR: SyntaxError: unterminated string literal - on startup

### ISSUE THREAD

**Issue by Flansi** [hacksider/Deep-Live-Cam#608]
Since the last commit, I'm encountering an error when starting the app:

python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Traceback (most recent call last):
  File "G:\App\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "G:\App\Deep-Live-Cam\modules\core.py", line 247, in run
    for frame_processor in get_frame_processors_modules(modules.globals.frame_processors):
  File "G:\App\Deep-Live-Cam\modules\processors\frame\core.py", line 38, in get_frame_processors_modules
    frame_processor_module = load_frame_processor_module(frame_processor)
  File "G:\App\Deep-Live-Cam\modules\processors\frame\core.py", line 23, in load_frame_processor_module
    frame_processor_module = importlib.import_module(f'modules.processors.frame.{frame_processor}')
  File "C:\Users\hanne\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\App\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 21
    conditional_download(download_directory_path, ['https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128.onnx])
                                                   ^
SyntaxError: unterminated string literal (detected at line 21)

![startuperror](https://github.com/user-attachments/assets/5f29d656-af26-4bd1-b752-f987fd5a38e6)

I have freshly cloned the repository but I'm still encountering this error.
(Windows 11, RTX 4090, Python 3.10.9)

**Comment by hacksider** [comment]
Download the inswapper_128 at https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128.onnx

and put it at the models folder

**Comment by Flansi** [comment]
I have the inswapper_128.onnx file in my models folder, and I downloaded the file you linked, but the error persists. The commit e1a01cfba20968ade73afbebd21ceb4888593210 works perfectly, so it seems like only the latest commit is causing issues.

**Comment by hacksider** [comment]
Did you download it manually? Because the old one have fp16 on it.

**Comment by Flansi** [comment]
downloaded it manually
i have both files in my models folder, tried deleting the inswapper_128_fp16.onnx file but it did not fiy the issue.

When I revert to commit e1a01cfba20968ade73afbebd21ceb4888593210, everything works fine, so the problem seems to be with the latest commit.

Thank you for your quick responses; I really appreciate your help!

**Comment by Flansi** [comment]
Ok i found the error. 
in the file face_swapper.py on line 21 there is a " ' " missing and the end of the download link.
i added the missing ' and now it starts!

**Comment by hacksider** [comment]
Lack of sleep 😅 thanks for noticing it though 🤭
