### ISSUE TITLE
Can't run the app: failed:Protobuf parsing failed

### ISSUE THREAD

**Issue by donnadulcinea** [hacksider/Deep-Live-Cam#613]
Hello everybody, I need your help.
So far I have tried to:

1. deleting model: inswapper_128_fp16.onnx
2. deleting the html descriptor automatically downloaded: inswapper_128_fp16.onnx
3. Downloading a differend model as suggested in:
    * The replacement version as suggested in https://github.com/hacksider/Deep-Live-Cam?tab=readme-ov-file#3-download-models
    * The one suggested here: https://github.com/hacksider/Deep-Live-Cam/issues/560#issuecomment-2339426093

I also tried:
* With and without CUDA
* With different face samples

With no success. What am I doing wrong?

 The stacktrace will follow:
```
(.venv) PS C:\Users\dulci\Documents\Development\Deep-Live-Cam> python .\run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dulci/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dulci/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dulci/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dulci/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dulci/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dulci\.pyenv\pyenv-win\versions\3.10.6\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\ui.py", line 141, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview(root))
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\ui.py", line 458, in webcam_preview
    create_webcam_preview()
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\ui.py", line 498, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 65, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 49, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 44, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model      
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model      
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__       
    super().__init__(model_path, **kwargs)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\dulci\Documents\Development\Deep-Live-Cam\models\inswapper_128.onnx failed:Protobuf parsing failed.
```

**Comment by hacksider** [comment]
kindly download https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128.onnx and put it in the model folder

**Comment by donnadulcinea** [comment]
This model works thank you! I didn't find it anwywhere before.
Thanks.

**Comment by Babix231** [comment]
Hello i have the same issue but i try to change the model by this one https://github.com/hacksider/Deep-Live-Cam/issues/613#issuecomment-2365159839 but i keep have the same issue ! Thanks !
