### ISSUE TITLE
Live webcam doesn't show up

### ISSUE THREAD

**Issue by chikiuso** [hacksider/Deep-Live-Cam#638]
Good morning,

  After running "python3 run.py --execution-provider coreml" on my macOS , it shows the setting screen but not showing the webcam screen, even after I clicked the Live button, and I checked the error message , something like :

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/albumentations/check_version.py:49: UserWarning: Error fetching version info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
  data = fetch_version_info()
2024-09-26 10:35:39.243 Python[8719:64315] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/l0/647x76dj7r9bdlj8rgdm1gg40000gn/T/org.python.python.savedState
2024-09-26 10:35:50.495 Python[8719:64315] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

Does anyone know how to solve it? thanks! I already install the Xcode-select

**Comment by Updatedme** [comment]
Can you provide the full error responses or drop a screenshot. I will be glad to help

**Comment by egomesrp** [comment]
![Captura de tela 2024-10-12 200424](https://github.com/user-attachments/assets/31c792e7-adf4-4c0c-90dd-88c723501358)

I'm having the same problem, can you help me? When I click on live, the screen goes blank and nothing shows up.

**Comment by LambAlp101** [comment]
You need activation link

**Comment by lihaorong840506** [comment]
Same problem in my running case, cannot run video mode

`Traceback (most recent call last):
  File "C:\Users\leehy\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\leehy\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\playground\Deep-Live-Cam\modules\ui.py", line 336, in <lambda>
    command=lambda: webcam_preview(
  File "D:\playground\Deep-Live-Cam\modules\ui.py", line 750, in webcam_preview
    create_webcam_preview(camera_index)
  File "D:\playground\Deep-Live-Cam\modules\ui.py", line 809, in create_webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "D:\playground\Deep-Live-Cam\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\leehy\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\Users\leehy\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\retinaface.py", line 213, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'`

**Comment by hacksider** [comment]
I would suggest using a face without any beard or that shows the full detail of the face. It can't detect a lot of hairy faces as of this moment
