### ISSUE TITLE
[Solved] Transparent UI and tkinter error

### ISSUE THREAD

**Issue by KRSHH** [hacksider/Deep-Live-Cam#656]
Error -
```
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter_init_.py", line 1921, in call
return self.func(*args)
File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter_init_.py", line 839, in callit
func(*args)
File "G:\App\Deep-Live-Cam - unchanged\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
window.block_update_dimensions_event()
File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter_init_.py", line 2383, in getattr
return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
```

Solution -
Open terminal in Deep-Live-Cam folder, enter these two commands -

```
1. .\venv\Scripts\Activate
2. python -m pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
```

**Comment by ExploreCrypto** [comment]
that fixed it thanks

**Comment by Updatedme** [comment]
This has been exceptionally helpful. 
Please leave it pinned down for quick access.
