### ISSUE TITLE
Live Cam Issue - Latest version

### ISSUE THREAD

**Issue by markbland82** [hacksider/Deep-Live-Cam#663]
![image](https://github.com/user-attachments/assets/d0a5efbb-f95a-4193-8d8c-00f757167ee2)
This is what live cam seems to do now. Seeing if I can fix it but so far the latest commit is not working. Any ideas? Thanks!

**Comment by KRSHH** [comment]
what does the error message say?

**Comment by markbland82** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\ui.py", line 409, in <lambda>
    command=lambda: webcam_preview(root),
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\ui.py", line 967, in webcam_preview
    create_webcam_preview()
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\ui.py", line 1018, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 65, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 49, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 44, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from H:\AI\RealTimeFaceSwap\Updated Version\Deep-Live-Cam\models\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by markbland82** [comment]
Had to use replacement file. Thanks!

**Comment by ronitosan** [comment]
What replacement file?

**Comment by GhoulBoii** [comment]
> What replacement file?

https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx (in the readme as well)
