### ISSUE TITLE
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

### ISSUE THREAD

**Issue by nitinmukesh** [hacksider/Deep-Live-Cam#668]
Installation went fine. Error appears with the following command and UI does not show.

python run.py --execution-provider cuda

I also tried replacing the models
![image](https://github.com/user-attachments/assets/53316a05-427e-4b2b-8969-2284bd299ced)

pip install --upgrade insightface

```
(venv) C:\ai\Deep-Live-Cam>python run.py --execution-provider cuda
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\ai\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
```

```
(venv) C:\ai\Deep-Live-Cam>pip list
Package                      Version
---------------------------- ---------------
absl-py                      2.1.0
addict                       2.4.0
albumentations               1.3.1
astunparse                   1.6.3
basicsr                      1.4.2
beautifulsoup4               4.12.3
cachetools                   5.5.0
certifi                      2024.8.30
charset-normalizer           3.3.2
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.3.0
customtkinter                5.2.2
cycler                       0.12.1
Cython                       3.0.11
darkdetect                   0.8.0
easydict                     1.13
facexlib                     0.3.0
filelock                     3.16.1
filterpy                     1.4.5
flatbuffers                  24.3.25
fonttools                    4.54.1
future                       1.0.0
gast                         0.4.0
gdown                        5.2.0
gfpgan                       1.3.8
google-auth                  2.35.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.66.2
h5py                         3.12.1
humanfriendly                10.0
idna                         3.10
imageio                      2.35.1
importlib_metadata           8.5.0
insightface                  0.7.3
jax                          0.4.33
jaxlib                       0.4.33
Jinja2                       3.1.4
joblib                       1.4.2
keras                        2.12.0
kiwisolver                   1.4.7
lazy_loader                  0.4
libclang                     18.1.1
llvmlite                     0.43.0
lmdb                         1.5.1
Markdown                     3.7
MarkupSafe                   2.1.5
matplotlib                   3.9.2
ml_dtypes                    0.5.0
mpmath                       1.3.0
networkx                     3.3
numba                        0.60.0
numpy                        1.24.3
oauthlib                     3.2.2
onnx                         1.16.0
onnxruntime-gpu              1.16.3
opencv-python                4.8.1.78
opencv-python-headless       4.10.0.84
opennsfw2                    0.10.2
opt_einsum                   3.4.0
packaging                    24.1
Pillow                       9.5.0
pip                          22.2.1
platformdirs                 4.3.6
prettytable                  3.11.0
protobuf                     4.23.2
psutil                       5.9.8
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pyparsing                    3.1.4
pyreadline3                  3.5.4
PySocks                      1.7.1
python-dateutil              2.9.0.post0
PyYAML                       6.0.2
qudida                       0.0.4
requests                     2.32.3
requests-oauthlib            2.0.0
rsa                          4.9
scikit-image                 0.24.0
scikit-learn                 1.5.2
scipy                        1.14.1
setuptools                   63.2.0
six                          1.16.0
soupsieve                    2.6
sympy                        1.13.3
tb-nightly                   2.19.0a20240930
tensorboard                  2.12.3
tensorboard-data-server      0.7.2
tensorflow                   2.12.1
tensorflow-estimator         2.12.0
tensorflow-intel             2.12.1
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
threadpoolctl                3.5.0
tifffile                     2024.9.20
tk                           0.1.0
tkinterdnd2                  0.4.2
tomli                        2.0.1
torch                        2.0.1+cu118
torchvision                  0.15.2+cu118
tqdm                         4.66.4
typing_extensions            4.5.0
urllib3                      2.2.3
wcwidth                      0.2.13
Werkzeug                     3.0.4
wheel                        0.44.0
wrapt                        1.14.1
yapf                         0.40.2
zipp                         3.20.2

```

**Comment by nitinmukesh** [comment]
Solved using

python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
