### ISSUE TITLE
Windows 10 install ; Application loads but is barely visible ; 

### ISSUE THREAD

**Issue by ExploreCrypto** [hacksider/Deep-Live-Cam#672]
**Describe the bug**

the app pops up and appears to have all functionality but is barely visible; Below is start of the App;
Any suggestions on adjusting the pop up display?

python run.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\13057\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\13057\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\13057\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\13057\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by KRSHH** [comment]
Check the pinned issue

**Comment by KRSHH** [comment]
[Issue solved](https://github.com/hacksider/Deep-Live-Cam/issues/656#issuecomment-2385979634)
