### ISSUE TITLE
When clicking Live, Camera preview is blank

### ISSUE THREAD

**Issue by ronitosan** [hacksider/Deep-Live-Cam#680]
Frame processor face_enhancer not found
Frame processor face_enhancer not found
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\Python 3.10\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\modules\ui.py", line 409, in <lambda>
    command=lambda: webcam_preview(root),
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\modules\ui.py", line 967, in webcam_preview
    create_webcam_preview()
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\modules\ui.py", line 1015, in create_webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\ronitosan\Downloads\Compressed\Deep-Live-Cam-main\modules\face_analyser.py", line 22, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

![image](https://github.com/user-attachments/assets/ce6905d4-c262-4442-88a6-9adeec44151b)

Can anyone point me to the right direction?

**Comment by tttyne** [comment]
Same problem

**Comment by thanhngochoang** [comment]
`[ WARN:2@166.791] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -2147023901
[ WARN:2@166.797] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -2147023901
[ WARN:0@166.804] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147023901`
Same problem
