### ISSUE TITLE
Exception in Tkinter callback Traceback (most recent call last):

### ISSUE THREAD

**Issue by cts85** [hacksider/Deep-Live-Cam#690]
After purchasing the Deep-Live-Cam Zero-Installation kit and installing it, I am facing the following error.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Marky\Desktop\DeepLive paid windows installer\Deep-Live-Cam-cuda\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Marky\Desktop\DeepLive paid windows installer\Deep-Live-Cam-cuda\python\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\Marky\Desktop\DeepLive paid windows installer\Deep-Live-Cam-cuda\python\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\Marky\Desktop\DeepLive paid windows installer\Deep-Live-Cam-cuda\python\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

The program did start after this error, but almost invisible in my screen. Please see the attached screenshot.
I did manage to make it work but the program is absurdly slow, like I can't even run it and the face swapped image result is too large and zoomed in, and I can't reduce it.
I had the 1.3 version of the software before and it ran smoothly, never had any problems with it. Can someone please help?

Below are my computer specS for reference:
Processor: 13th Gen Intel Core i9 
Graphics: NVIDIA GeForce RTX 4090 16GB VRAM 
RAM: 32GB

![error](https://github.com/user-attachments/assets/31f97900-ec18-4f5f-892d-fab5305bacbd)

**Comment by KRSHH** [comment]
Again, please check the pinned issues before opening another one.

**Comment by KRSHH** [comment]
#656

**Comment by GitGuardianX** [comment]
The solution is not working for me.  I am trying to activate a virtual environment in PowerShell by running the command .\venv\Scripts\Activate, but encountering an error. The error message indicates that the term '.\venv\Scripts\Activate' is not recognized as a cmdlet, function, script file, or operable program. 

![04-10-2024 (155)](https://github.com/user-attachments/assets/6997c14f-b7e0-4b49-8263-89cb367d8424)
