### ISSUE TITLE
Error: INVALID_PROTOBUF parsing failed in macOS M1(Apple Silicon)

### ISSUE THREAD

**Issue by nevidomyy** [hacksider/Deep-Live-Cam#697]
I have this error on macOS Apple Silicon.
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users//PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/ui.py", line 242, in <lambda>
    command=lambda: webcam_preview(
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/ui.py", line 649, in webcam_preview
    create_webcam_preview(
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/ui.py", line 707, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 65, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 49, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/Users/PycharmProjects/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 44, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
  File "/Users/PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/Users/PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/Users/PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/Users/PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/PycharmProjects/Deep-Live-Cam/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/PycharmProjects/Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`

This https://github.com/hacksider/Deep-Live-Cam/issues/613 didn't help.

**Comment by suresh-3x** [comment]
Same error on M2 air.

I just completed the setup and tried both "inswapper" models.


`Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/ui.py", line 242, in <lambda>
    command=lambda: webcam_preview(
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/ui.py", line 649, in webcam_preview
    create_webcam_preview(camera_index)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/ui.py", line 707, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 65, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 49, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 44, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/suresh-3x/Work/Deep-Live-Cam/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/suresh-3x/Work/Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.
`

**Comment by suresh-3x** [comment]
Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.

**Comment by nevidomyy** [comment]
Yes this model work! But very low fps. Maybe on windows and nvidia works fine. (

**Comment by nevidomyy** [comment]
> Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.

Yes this model work! But very low fps. Maybe on windows and nvidia works fine. (

**Comment by zhoufanglu** [comment]
> Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.

it's work, thanks

**Comment by leihuayi** [comment]
> Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.

This model not not work for me (running on Debian with CUDA), I get a 47MB file, while the 265MB file from github assets mentioned in #717 works correctly.

**Comment by hacksider** [comment]
> > Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.
> 
> This model not not work for me (running on Debian with CUDA), I get a 47MB file, while the 265MB file from github assets mentioned in #717 works correctly.

Thhere might be a problem on your download since it's 277mb and not 47mb
![image](https://github.com/user-attachments/assets/ff03af26-1876-4e05-b66b-988fb6475665)

**Comment by ConnoisseurProtege** [comment]
> > > Download [this](https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx) model and put it inside the models folder. This fixed the issue for me.
> > 
> > 
> > This model not not work for me (running on Debian with CUDA), I get a 47MB file, while the 265MB file from github assets mentioned in #717 works correctly.
> 
> Thhere might be a problem on your download since it's 277mb and not 47mb ![image](https://private-user-images.githubusercontent.com/1267200/376288275-ff03af26-1876-4e05-b66b-988fb6475665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTI5NDAsIm5iZiI6MTczMDUxMjY0MCwicGF0aCI6Ii8xMjY3MjAwLzM3NjI4ODI3NS1mZjAzYWYyNi0xODc2LTRlMDUtYjY2Yi05ODhmYjY0NzU2NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMDE1NzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI3YzkxNjM0MTgxNjhmYmQ3ZDNiZDI0Njk3YTdiZjVmZGEyZTI2ODY5N2Q2NTZhMjliZjY2YTI4NDQwYzAwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hE9QniSL3IjEvXjKhDXOfKkxiUE9zOOZTcCRC6emJsA)

Is this the same model as the one linked in the readme? I noticed that the one I downloaded thru the link is much larger and isn't named the same?(doesn't seem to be fp16)

**Comment by Anth772** [comment]
Hello good morning and amazing day
