### ISSUE TITLE
Error when I try "live", Exception in Tkinter callback

### ISSUE THREAD

**Issue by VikentiyAlfons** [hacksider/Deep-Live-Cam#699]
Error when I try "live"

already tried python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl, didn't help. 
I did everything in venv.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Dimass\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\AI\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\AI\Deep-Live-Cam\modules\ui.py", line 253, in <lambda>
    command=lambda: webcam_preview(
  File "D:\AI\Deep-Live-Cam\modules\ui.py", line 660, in webcam_preview
    create_webcam_preview(camera_index)
  File "D:\AI\Deep-Live-Cam\modules\ui.py", line 732, in create_webcam_preview
    if modules.globals.show_fps:
AttributeError: module 'modules.globals' has no attribute 'show_fps'

![изображение](https://github.com/user-attachments/assets/4b464b7c-5d55-4cd4-8333-f64ca888b3bf)

**Comment by razkaoui1** [comment]
i have same problem
<\Deep-Live-Cam\modules\ui.py", line 732, in create_webcam_preview
    if modules.globals.show_fps:
AttributeError: module 'modules.globals' has no attribute 'show_fps'
>

**Comment by KRSHH** [comment]
Pull again

**Comment by wbr201** [comment]
me to

**Comment by wbr201** [comment]
me too
