### ISSUE TITLE
AttributeError: module 'modules.processors.frame.face_enhancer' has no attribute 'process_frame_v2'

### ISSUE THREAD

**Issue by Zongwei-Tang** [hacksider/Deep-Live-Cam#719]
I finally run the program, but when I turn on face enhancer it got the following error: 

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.20/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/citrusfurina/myenv/lib/python3.9/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/Users/citrusfurina/Desktop/Deep-Live-Cam/modules/ui.py", line 866, in <lambda>
    POPUP_LIVE, text="Submit", command=lambda: on_submit_click()
  File "/Users/citrusfurina/Desktop/Deep-Live-Cam/modules/ui.py", line 850, in on_submit_click
    create_webcam_preview(camera_index)
  File "/Users/citrusfurina/Desktop/Deep-Live-Cam/modules/ui.py", line 797, in create_webcam_preview
    temp_frame = frame_processor.process_frame_v2(temp_frame)
AttributeError: module 'modules.processors.frame.face_enhancer' has no attribute 'process_frame_v2'

However, if I dont turn on face enhancer, the program can run smoothly. 

The program is ran on MacBook Air M3. 

Is there anything I can do to fix this?

**Comment by KRSHH** [comment]
Thanks for reporting, Pull again

**Comment by KRSHH** [comment]
> i really need some guide in setting this amazing program up on my pc

Instructions to install it are on README.
