### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by alex-ac-ir** [hacksider/Deep-Live-Cam#720]
```
set det-size: (640, 640)
2024-10-16 22:34:44.5789967 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Software\DeepFake\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Software\DeepFake\python\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\Software\DeepFake\modules\ui.py", line 141, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview(root))
  File "D:\Software\DeepFake\modules\ui.py", line 458, in webcam_preview
    create_webcam_preview()
  File "D:\Software\DeepFake\modules\ui.py", line 495, in create_webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "D:\Software\DeepFake\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
  File "D:\Software\DeepFake\python\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "D:\Software\DeepFake\python\lib\site-packages\insightface\model_zoo\retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
  File "D:\Software\DeepFake\python\lib\site-packages\insightface\model_zoo\retinaface.py", line 152, in forward
    net_outs = self.session.run(self.output_names, {self.input_name : blob})
  File "D:\Software\DeepFake\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
```

On a laptop MSI with NVIDIA GeForce GTX 960M, I guess it has 2Gb

Any clue how to fix it ?

Adding a screenshot also:

**Comment by hacksider** [comment]
The minimum requirement running this on nvidia is 6gb VRAM

**Comment by hacksider** [comment]
As for the Cuda error, your GPU is not compatible with the CUDA version you're running.
