### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2_enumerate_cameras'

### ISSUE THREAD

**Issue by marsonal2023** [hacksider/Deep-Live-Cam#729]
Traceback (most recent call last):
  File "F:\New folder (2)\Deeplivecam Portable\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "F:\New folder (2)\Deeplivecam Portable\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "F:\New folder (2)\Deeplivecam Portable\Deep-Live-Cam\modules\ui.py", line 6, in <module>
    from cv2_enumerate_cameras import enumerate_cameras  # Add this import
ModuleNotFoundError: No module named 'cv2_enumerate_cameras'
Press any key to continue . . .

**Comment by hacksider** [comment]
pip install cv2_enumerate_cameras

**Comment by marsonal2023** [comment]
this doesnt solve the problem , error still present
