### ISSUE TITLE
Issue with CV2_enumerate_cameras

### ISSUE THREAD

**Issue by jay0233** [hacksider/Deep-Live-Cam#734]
Hi,

I've installed cv2_enumerate_cameras but when i run deep-live-cam I get the following:

Traceback (most recent call last):
  File "C:\Programs\Python\Deep-Live-Cam-main\run.py", line 3, in <module>
    from modules import core
  File "C:\Programs\Python\Deep-Live-Cam-main\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Programs\Python\Deep-Live-Cam-main\modules\ui.py", line 6, in <module>
    from cv2_enumerate_cameras import enumerate_cameras  # Add this import
  File "C:\Users\x\miniconda3\lib\site-packages\cv2_enumerate_cameras\__init__.py", line 15, in <module>
    from cv2_enumerate_cameras.windows_backend import supported_backends, cameras_generator
  File "C:\Users\x\miniconda3\lib\site-packages\cv2_enumerate_cameras\windows_backend.py", line 2, in <module>
    from cv2_enumerate_cameras._windows_backend import MSMF_enumerate_cameras, DSHOW_enumerate_cameras
ModuleNotFoundError: No module named 'cv2_enumerate_cameras._windows_backend'

The file _windows_backend.pyi is present in the cv2_enumerate_cameras folder. 

Any suggestions?

**Comment by KRSHH** [comment]
Open terminal in Deep-Live-Cam folder, enter these two commands -

```
.\venv\Scripts\Activate  - (If you are running it in a venv)
```

```
python -m pip install --force-reinstall cv2_enumerate_cameras==1.1.15
```
