### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:  deep-Live-Cam/modules/..\\models\\GFPGANv1.4.pth

### ISSUE THREAD

**Issue by sammyjank** [hacksider/Deep-Live-Cam#75]
Hi, Im on linux, having the following issue  when trying to use the face enhancer option.:

[DLC.FACE-SWAPPER] Progressing...
[DLC.FACE-ENHANCER] Progressing...
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/trev/appz/_venvs/deepLiveCam_hacksider/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/ui.py", line 95, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/ui.py", line 192, in select_output_path
    start()
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/core.py", line 182, in start
    frame_processor.process_image(modules.globals.source_path, modules.globals.output_path, modules.globals.output_path)
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/processors/frame/face_enhancer.py", line 70, in process_image
    result = process_frame(None, target_frame)
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/processors/frame/face_enhancer.py", line 55, in process_frame
    temp_frame = enhance_face(temp_frame)
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/processors/frame/face_enhancer.py", line 45, in enhance_face
    _, _, temp_frame = get_face_enhancer().enhance(
  File "/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/processors/frame/face_enhancer.py", line 39, in get_face_enhancer
    FACE_ENHANCER = gfpgan.GFPGANer(model_path=model_path, upscale=1) # type: ignore[attr-defined]
  File "/home/trev/appz/_venvs/deepLiveCam_hacksider/lib/python3.10/site-packages/gfpgan/utils.py", line 92, in __init__
    loadnet = torch.load(model_path)
  File "/home/trev/appz/_venvs/deepLiveCam_hacksider/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/trev/appz/_venvs/deepLiveCam_hacksider/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/trev/appz/_venvs/deepLiveCam_hacksider/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/trev/appz/faceSwapApps/deep-Live-Cam/modules/..\\models\\GFPGANv1.4.pth'

It only works without face enhancer...  Both models are in the right folder /models
On windows face enhancer works fine. 

Any suggestion would be appreciated.

**Comment by mars7233** [comment]
@sammyjank Encountered the same issue

**Comment by hacksider** [comment]
Kindly pull the latest commit

**Comment by sammyjank** [comment]
Sweet, it is working now! Thanks
