### ISSUE TITLE
new version I face this issue after try to lunch for two images or live ..

### ISSUE THREAD

**Issue by hlafmanta** [hacksider/Deep-Live-Cam#750]
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Obito/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Obito/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Obito/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Obito/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Obito/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[DLC.CORE] Processing...
[DLC.FACE-SWAPPER] Progressing...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 299, in <lambda>
    root, text="Start", cursor="hand2", command=lambda: analyze_target(start, root)
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 383, in analyze_target
    select_output_path(start)
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 642, in select_output_path
    start()
  File "C:\asd\Deep-Live-Cam-main\modules\core.py", line 189, in start
    frame_processor.process_image(modules.globals.source_path, modules.globals.output_path, modules.globals.output_path)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 233, in process_image
    result = process_frame(source_face, target_frame)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 107, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 65, in swap_face
    face_swapper = get_face_swapper()
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 58, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\asd\Deep-Live-Cam-main\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.
[DLC.CORE] Processing...
[DLC.FACE-SWAPPER] Progressing...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 299, in <lambda>
    root, text="Start", cursor="hand2", command=lambda: analyze_target(start, root)
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 383, in analyze_target
    select_output_path(start)
  File "C:\asd\Deep-Live-Cam-main\modules\ui.py", line 642, in select_output_path
    start()
  File "C:\asd\Deep-Live-Cam-main\modules\core.py", line 189, in start
    frame_processor.process_image(modules.globals.source_path, modules.globals.output_path, modules.globals.output_path)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 233, in process_image
    result = process_frame(source_face, target_frame)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 107, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 65, in swap_face
    face_swapper = get_face_swapper()
  File "C:\asd\Deep-Live-Cam-main\modules\processors\frame\face_swapper.py", line 58, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Obito\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
```

**Comment by hacksider** [comment]
Please use the template we created when reporting a bug.
