### ISSUE TITLE
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' 

### ISSUE THREAD

**Issue by zzxxchen** [hacksider/Deep-Live-Cam#764]
Hello,
When i try to lunch run.py i get these errors:
I've installed python 3.10.0.

**Error Message**
```
(venv) D:\Program\Deep-Live-Cam-main-11.1>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "D:\Program\Deep-Live-Cam-main-11.1\run.py", line 3, in <module>
    from modules import core
  File "D:\Program\Deep-Live-Cam-main-11.1\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "D:\Program\Deep-Live-Cam-main-11.1\modules\ui.py", line 13, in <module>
    from modules.face_analyser import (
  File "D:\Program\Deep-Live-Cam-main-11.1\modules\face_analyser.py", line 4, in <module>
    import insightface
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\__init__.py", line 17, in <module>
    from .augmentations import *
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
    from .blur.functional import *
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
    from .functional import *
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\blur\functional.py", line 12, in <module>
    from albumentations.augmentations.functional import convolve
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\functional.py", line 34, in <module>
    import albumentations.augmentations.geometric.functional as fgeometric
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\geometric\__init__.py", line 2, in <module>
    from .resize import *
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\albumentations\augmentations\geometric\resize.py", line 8, in <module>
    from pydantic import Field, ValidationInfo, field_validator
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\pydantic\__init__.py", line 411, in __getattr__
    module = import_module(module_name, package=package)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\pydantic\fields.py", line 20, in <module>
    from . import types
  File "D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\pydantic\types.py", line 37, in <module>
    from typing_extensions import Annotated, Literal, Protocol, TypeAlias, TypeAliasType, deprecated
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (D:\Program\Deep-Live-Cam-main-11.1\venv\lib\site-packages\typing_extensions.py)
```
**Desktop:**
 - OS: [Windows10]
 - Version [22H2]
 - GPU [NVIDIA GeForce GTX 1080 Ti]
 - CPU [Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz]

**Comment by Updatedme** [comment]
kindly download 
https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128.onnx and replace it in the model folder

Then run the 
python run.py --execution-provider cuda

**Comment by Updatedme** [comment]
Let me k ow if you got further error.  
( If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010 )
