### ISSUE TITLE
inswapper_128_fp16.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by shenmazzc** [hacksider/Deep-Live-Cam#769]
models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.  it's wrong

**Comment by hacksider** [comment]
Can you give more details about your issue? You can also download it manually based on the readme.

**Comment by sandrasoueid** [comment]
Having the same issue, tried both versions of inswapper_128 in the README

```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Sandra/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Sandra\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\ui.py", line 336, in <lambda> 
    command=lambda: webcam_preview(
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\ui.py", line 750, in webcam_preview
    create_webcam_preview(camera_index)
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\ui.py", line 816, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 107, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 65, in swap_face
    face_swapper = get_face_swapper()
  File "C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 58, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "c:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)       
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Sandra\Programming\start-up\playground\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.

```
