### ISSUE TITLE
Error when clicking preview

### ISSUE THREAD

**Issue by Beachwayyy** [hacksider/Deep-Live-Cam#782]
and btw, also just doesnt work when i click Live, my face just gets covered with a black square

(myenv) C:\Users\beach\Downloads\face\Deep-Live-Cam>python run.py --execution-provider cuda
2024-11-12 12:13:45.0124531 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\beach/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
2024-11-12 12:13:45.3754405 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\beach/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
2024-11-12 12:13:45.4361249 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\beach/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
2024-11-12 12:13:45.4925996 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\beach/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
2024-11-12 12:13:45.5894786 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\beach/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
2024-11-12 12:14:04.0241130 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
[DLC.CORE] Processing...
[DLC.FACE-SWAPPER] Progressing...
[DLC.CORE] Processing to image succeed!
[ERROR:0@0.001] global cap_ffmpeg_impl.hpp:1268 open Could not find decoder for codec_id=61
[ERROR:0@0.001] global cap_ffmpeg_impl.hpp:1317 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ WARN:0@66.742] global loadsave.cpp:241 cv::findDecoder imread_('C:/Users/beach/Downloads/{%01dB0BCE0B-6790-4945-A3F7-FBAFAA83E9B2}.png'): can't open/read file: check file path/integrity
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\beach\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\modules\ui.py", line 309, in <lambda>
    root, text="Preview", cursor="hand2", command=lambda: toggle_preview()
                                                          ^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\modules\ui.py", line 710, in toggle_preview
    update_preview()
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\modules\ui.py", line 732, in update_preview
    temp_frame = frame_processor.process_frame(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 107, in process_frame
    target_face = get_one_face(temp_frame)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beach\Downloads\face\Deep-Live-Cam\myenv\Lib\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
                     ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by 1146809051** [comment]
I've also encountered the same problem. Have you resolved it now?

**Comment by 1146809051** [comment]
@Beachwayyy I've also encountered the same problem. Have you resolved it now?

**Comment by hacksider** [comment]
This means you installed the wrong version of onnx-runtime. Check the version of the one you installed versus the one on the requirements.txt
