### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'  <-- somebody help me, plz

### ISSUE THREAD

**Issue by wonderbird2** [hacksider/Deep-Live-Cam#786]
(base) C:\Users\sksj0\Downloads\Deep-Live-Cam>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "C:\Users\sksj0\Downloads\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\sksj0\Downloads\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

-
I don't get it.. somebody help me. I try to fix about spend 9 hours for this.
anyone rescue me. plz
God, help me out!

**Comment by manasseh-zues** [comment]
use conda terminal not cmd or git

**Comment by codak77** [comment]
Run it in a virtual environment(venv). This is why

**Comment by davidlorex** [comment]
Did you create  an environment. 

I want to belive that you got this running on python 3.10

If you require my personal assistance, reach out to me on whatsapp +2347081306010
