### ISSUE TITLE
pls whats the problem with this new update

### ISSUE THREAD

**Issue by Diamondpmc** [hacksider/Deep-Live-Cam#793]
C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad>echo off
download_path: C:\Users\preck/.insightface\models\buffalo_l
Downloading C:\Users\preck/.insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\urllib3\connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\modules\ui.py", line 336, in <lambda>
    command=lambda: webcam_preview(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\modules\ui.py", line 750, in webcam_preview
    create_webcam_preview(camera_index)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\modules\ui.py", line 809, in create_webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\modules\face_analyser.py", line 22, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\insightface\utils\download.py", line 71, in download_file
    r = requests.get(url, stream=True)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\preck\Downloads\Deep-Live-Cam-Gumroad\venv\lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=None)

**Comment by hacksider** [comment]
It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.

**Comment by teslarecords** [comment]
> It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.

Can you help me, i replace 128.onnx - and face spawed, but the fps is +- 5-10, what is that?

**Comment by hacksider** [comment]
> > It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.
> 
> Can you help me, i replace 128.onnx - and face spawed, but the fps is +- 5-10, what is that?

Please create your own thread and dont hijack other threads please 😄 Also, please give more details as I cant magically know what your hardware is.

**Comment by teslarecords** [comment]
> > > It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.
> > 
> > 
> > Can you help me, i replace 128.onnx - and face spawed, but the fps is +- 5-10, what is that?
> 
> Please create your own thread and dont hijack other threads please 😄 Also, please give more details as I cant magically know what your hardware is.

i created the new thread, but this was delete

**Comment by teslarecords** [comment]
> > > It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.
> > 
> > 
> > Can you help me, i replace 128.onnx - and face spawed, but the fps is +- 5-10, what is that?
> 
> Please create your own thread and dont hijack other threads please 😄 Also, please give more details as I cant magically know what your hardware is.

rtx 4070, intel i5

**Comment by uzorsydney** [comment]
> It's trying to download the models again. You can actually just copy the tmp folder of your old one and upload it to the new one to avoid downloading the models again.

please how do I do this, it's the first time installing this on the pc and it's giving this error, you are saying to copy the tmp folder, what tmp folder? and you also say models by models do you mean the gfpgan and inswapper?
