### ISSUE TITLE
Assetion error- but models are in place in folder

### ISSUE THREAD

**Issue by lamb909** [hacksider/Deep-Live-Cam#794]
ERROR message when trying to run application
I have made sure models are in place 
but still same error
running on rtx3070 pc
using run cuda and run cpu does not work

Traceback (most recent call last):
  File "C:\iRoopDeepFaceCam\iRoopDeepFaceCam\run.py", line 6, in <module>
    core.run()
  File "C:\iRoopDeepFaceCam\iRoopDeepFaceCam\modules\core.py", line 267, in run
    initialize_face_analyser()
  File "C:\iRoopDeepFaceCam\iRoopDeepFaceCam\modules\face_analyser.py", line 42, in initialize_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\iRoopDeepFaceCam\iRoopDeepFaceCam\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by hacksider** [comment]
I think you're reporting an issue from a fork :) closing this as this is not from deep-live-cam
