### ISSUE TITLE
Preparing metadata (setup.py) ... error

### ISSUE THREAD

**Issue by GribStar** [hacksider/Deep-Live-Cam#802]
When running the command pip install -r requirements.txt
An error occurs
Collecting pillow==9.5.0 (from -r requirements.txt (line 11))
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-80l5f4wm\\pillow_70bccb2016634542966910302c98ae82\\setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-80l5f4wm\pillow_70bccb2016634542966910302c98ae82\setup.py", line 29, in <module>
          PILLOW_VERSION = get_version()
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-80l5f4wm\pillow_70bccb2016634542966910302c98ae82\setup.py", line 26, in get_version
          return locals()["__version__"]
                 ~~~~~~~~^^^^^^^^^^^^^^^
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What could be the problem?

**Comment by deviantintegral** [comment]
I had the same problem using python 3.12. I assumed newer versions would work, but the readme is correct in that you have to use python 3.10. Assuming you have python 3.10 installed somehow (sorry, I'm a linux user so not sure what you do on Windows):

```
python3.10 -m venv venv
```

**Comment by Updatedme** [comment]
If you need further help, you can reach out to me on whataap +2347081306010
