### ISSUE TITLE
Error when i click "start" in the program

### ISSUE THREAD

**Issue by Trader-Obs** [hacksider/Deep-Live-Cam#832]
I et this error message everytime i try to swap faces in the program. Please help.

`EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1748181368 ; hostname=DESKTOP-BT1JAKI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Windows\system32\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Windows\system32\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1748181368 ; hostname=DESKTOP-BT1JAKI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\.venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Windows\system32\Deep-Live-Cam\modules\ui.py", line 299, in <lambda>
    root, text="Start", cursor="hand2", command=lambda: analyze_target(start, root)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\Deep-Live-Cam\modules\ui.py", line 383, in analyze_target
    select_output_path(start)
  File "C:\Windows\system32\Deep-Live-Cam\modules\ui.py", line 642, in select_output_path
    start()
  File "C:\Windows\system32\Deep-Live-Cam\modules\core.py", line 176, in start
    if not frame_processor.pre_start():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 41, in pre_start
    elif not modules.globals.map_faces and not get_one_face(
                                               ^^^^^^^^^^^^^
  File "C:\Windows\system32\Deep-Live-Cam\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\Deep-Live-Cam\modules\face_analyser.py", line 22, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\.venv\Lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\.venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\.venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\system32\.venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Windows\system32\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Windows\system32\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Windows\system32\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1736413080 ; hostname=DESKTOP-BT1JAKI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);`

**Comment by hacksider** [comment]
Please include your hardware details as well

**Comment by Trader-Obs** [comment]
> Please include your hardware details as well

i use a dell latitude 7420
core i5
11th gen
up to 4.40Ghz for processing power

**Comment by hacksider** [comment]
It wont work as you dont have any nvidia GPU based on the specs you have given and you installed CUDA. Closing this now. Just use the CPU version

**Comment by Trader-Obs** [comment]
Help, now it shows this
`Traceback (most recent call last):
  File "C:\Windows\system32\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Windows\system32\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
  File "C:\Windows\system32\Deep-Live-Cam\.venv\Lib\site-packages\torch\__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.`
